### ISSUE TITLE
Copyright is missing

### ISSUE THREAD

**Issue by elboulangero** [containerd/fifo#14]
Dear containerd authors,

I would like to package this library for Debian, however I couldn't find a copyright anywhere. This should be mentioned in the LICENSE file as well, right now the copyright line there is just a template.

https://github.com/containerd/fifo/blob/fbfb6a11ec671efbe94ad1c12c2e98773f19e1e6/LICENSE#L189

Thanks

**Comment by dqminh** [comment]
@elboulangero for clarification, i think `Copyright [yyyy] [name of copyright owner]` should not be changed from the license file (i.e. we should not modify stock apache license). #15 added correct copyright header to file so it should be good.
